version: '2'
services:
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: passwordklean
    networks:
      gNetwork:
        ipv4_address: 172.20.0.2  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8000:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: passwordklean
    networks:
      gNetwork:
        ipv4_address: 172.20.0.3
  wordpress:
    depends_on:
      - db
    image: wordpress
    restart: always
    volumes:
      - ./wp-content:/var/www/html/wp-content
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD : passwordklean
    ports:
      - 8001:80
    networks:
      gNetwork:
        ipv4_address: 172.20.0.4
networks:
  gNetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
volumes:
  db_data: